Feat/bilinear interpolation
GIS-Suite/GribInterpolation pull request #14
Opened 2024-03-16 02:18 UTC by algo-rhythmical

BilinearInterpolator class: Interpolate the sea temperature values for the missing depths of data points at a given latitude/longitude.

2024-03-19 18:53 UTC, sechols223 requested changes
**The goal of this project is not to interpolate lat, lon, or depth but to interpolate temperature**

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +    public static ArrayList<DataPoint> InterpolateWithStaticLat(float[] targetLonLat, DataPoint upperDepthDataPoint1, DataPoint upperDepthDataPoint2, DataPoint lowerDepthDataPoint1, DataPoint lowerDe
Method names should be Camel Case.

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        double[] LonOfUDDP1AndUDDP2 = {upperDepthDataPoint1.getLongitude(), upperDepthDataPoint2.getLongitude()};
Variable names should be Camel Case

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        double[] LonOfLDDP1AndLDDP2 = {lowerDepthDataPoint1.getLongitude(), lowerDepthDataPoint2.getLongitude()};
Variable names should be Camel Case

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +                    (float)linearInterpolator.interpolate(upperAndLowerDepthOfDP1, temperatureOfUpperAndLowerDepth).value(depthLevel),
This logic should be extracted into a variable

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        double[] LatOfUDDP1AndUDDP2 = {upperDepthDataPoint1.getLatitude(), upperDepthDataPoint2.getLatitude()};
Variable names should be Camel Case

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        double[] LatOfLDDP1AndLDDP2 = {lowerDepthDataPoint1.getLatitude(), lowerDepthDataPoint2.getLatitude()};
Variable names should be Camel Case

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +                    (float)linearInterpolator.interpolate(upperAndLowerDepthOfDP1, temperatureOfUpperAndLowerDepth).value(depthLevel),
This logic should be extracted into a variable

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/Main.java
>      public static void main(String[] args) {
None of this should be in the `main` method or `Main` class

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        upperDepthTemp = linearInterpolator.interpolate(LonOfUDDP1AndUDDP2, tempsOfUDDP1AndUDDP2).value(targetLonLat[0]);
Variable and declaration can be inline

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        lowerDepthTemp = linearInterpolator.interpolate(LonOfLDDP1AndLDDP2, tempsOfLDDP1AndLDDP2).value(targetLonLat[0]);
Variable and declaration can be inline

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        for (double depthLevel = upperDepthDataPoint1.getDepth() + 1; depthLevel < lowerDepthDataPoint1.getDepth(); depthLevel++) {
We don't need to make new depths. The latitude, longitude, and depths are already known points are the earth.

2024-03-19 18:53 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
The goal of this project is not to interpolate lat, lon, or depth but to interpolate temperature

2024-03-19 19:59 UTC, algo-rhythmical commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
The only thing that is being interpolated in BilinearInterpolator is temperature. noted on lines 18, 23, 56, 61.

2024-03-19 20:02 UTC, algo-rhythmical commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +        for (double depthLevel = upperDepthDataPoint1.getDepth() + 1; depthLevel < lowerDepthDataPoint1.getDepth(); depthLevel++) {
So we are not creating the missing data points?

2024-03-23 21:06 UTC, sechols223 requested changes
There are some changes that need to be made before approval

2024-03-23 21:06 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
Can you make your variable names clearer/more readable?

For instance, instead of:
`double[] lonOfLDDP1AndLDDP2`
It could be:
`double[] longitudes`
Or
`double[] datapointLongitudes`

This way if someone else needs to be looking over or modifying this code it's more clear to them.

2024-03-23 21:06 UTC, sechols223 commented on src/test/java/com/github/gissuite/gribinterpolation/BilinearInterpolatorTest.java
> +    public void bilinearInterpolatorTest() {
The name of this method should be something along the lines of:
`bilinearInterpolation_Should_Return_DataPoint`

I know this is incredibly verbose and long but this normally the naming convention for unit tests and integration tests

2024-03-23 21:06 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/BilinearInterpolator.java
> +    public static DataPoint interpolateWithDynamicLon(float[] targetLonLat, float targetDepth,DataPoint upperDepthDataPoint1, DataPoint upperDepthDataPoint2, DataPoint lowerDepthDataPoint1, DataPoint
`float[] targetLonLat` and `float targetDepth` should be changed to `DataPoint interpolationPoint`

2024-03-23 21:06 UTC, sechols223 commented on src/test/java/com/github/gissuite/gribinterpolation/BilinearInterpolatorTest.java
> +    public void bilinearInterpolatorTest() {
Break these up I to separate unit test methods in this class. The convention is your unit test method should only be testing the output of a singular methods return value

2024-03-24 01:21 UTC, sechols223 approved these changes
Good Job 😃

2024-03-24 01:21 UTC, merged