Feat/run config read grib files
GIS-Suite/GribInterpolation pull request #2
Opened 2024-02-01 17:20 UTC by algo-rhythmical

Use the grib files' folder path as command line argument. 
Run Main to read all grib files.

2024-02-01 23:42 UTC, woycy commented on src/main/java/org/example/Main.java
> +                    System.out.println(gribFileNames[i]);
Just a nitpick, might want to switch the order of the print statement and declaring gribFileName since they reference the same thing and you then wouldn't have to reference the array twice

2024-02-06 00:34 UTC, JakeIsCodingAway requested changes
see comments that were made

2024-02-06 00:34 UTC, JakeIsCodingAway commented on src/main/java/org/example/Main.java
> +                //Combining folder path with grib file name to create full grib file path to read all grib files
change this to something like the following

File folderPath = new File(args[0]);
if(folderPath.exists(){
 // do thing
} else {
tell user that directory doesnt exist
}

on the if statement on line 19, just do a check for length != 0, i dont thing FIle.list() will ever return null, please verify though

2024-02-06 00:34 UTC, JakeIsCodingAway commented on src/main/java/org/example/Main.java
> +                    String gribFilePath = folderPath + "\\" + gribFileName;
This is fine for right now, but know that there are other filesystems than what windows uses, and they use different delineators for file seperators. I.E. this will not work on linux. See if there is a File.getChilderen or File.getFiles, and then iterate through that file object and check that it isnt a directory. that way you still iterate through the files, but dont make yourself beholden to file systems

2024-02-06 17:29 UTC, merged