Feat/nearest neighbor
GIS-Suite/GribInterpolation pull request #36
Opened 2024-04-10 02:49 UTC by ynydara

gets the nearest neighbors for knn algorithm

2024-04-10 02:51 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighborAlgorithm.java
> +public class NearestNeighborAlgorithm {
This whole file shouldn't exist

2024-04-10 02:56 UTC, sechols223 requested changes

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +public class NearestNeighbor {
add a line after the class

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighborAlgorithm.java
> +public class NearestNeighborAlgorithm {
This whole file shouldn't exist

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +private static Map<DataPoint, Double> sortByValue(HashMap<DataPoint, Double> map) {
Private methods should go below public ones

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +    public static DataPoint[] getNearestNeighbor(DataPoint[] dataPoint, float longitudeToInterpolate, float latitudeToInterpolate, int k, int amountOfDataPoints) {
Please create proper documentation for this method

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +    public static DataPoint[] getNearestNeighbor(DataPoint[] dataPoint, float longitudeToInterpolate, float latitudeToInterpolate, int k, int amountOfDataPoints) {
the `dataPoint` parameter should be plural because it's an array

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +    public static DataPoint[] getNearestNeighbor(DataPoint[] dataPoint, float longitudeToInterpolate, float latitudeToInterpolate, int k, int amountOfDataPoints) {
the `dataPoint` parameter should be an ArrayList

2024-04-10 02:56 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +        return nearestNeighbors;
The output of this method should be an ArrayList

2024-04-10 04:05 UTC, ynydara commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +        return nearestNeighbors;
ok done

2024-04-10 04:05 UTC, ynydara commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +    public static DataPoint[] getNearestNeighbor(DataPoint[] dataPoint, float longitudeToInterpolate, float latitudeToInterpolate, int k, int amountOfDataPoints) {
done

2024-04-10 04:06 UTC, ynydara commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +    public static DataPoint[] getNearestNeighbor(DataPoint[] dataPoint, float longitudeToInterpolate, float latitudeToInterpolate, int k, int amountOfDataPoints) {
hopefully done :)

2024-04-10 04:06 UTC, ynydara commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +private static Map<DataPoint, Double> sortByValue(HashMap<DataPoint, Double> map) {
done

2024-04-10 04:06 UTC, ynydara commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighborAlgorithm.java
> +public class NearestNeighborAlgorithm {
deleted

2024-04-10 04:06 UTC, ynydara commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +public class NearestNeighbor {
done

2024-04-10 19:01 UTC, sechols223 requested changes

2024-04-10 19:01 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/NearestNeighbor.java
> +public class NearestNeighbor {
Use this as a reference for creating proper documentation using Javadoc:
https://www.baeldung.com/javadochttps://www.baeldung.com/javadoc

2024-04-23 02:43 UTC, sechols223 approved these changes

2024-04-23 02:43 UTC, merged