Alliesbranch2
GIS-Suite/GribInterpolation pull request #40
Opened 2024-04-24 18:41 UTC by alemmond

Created a file that reads an array list of data points with known and unknown temperatures and returns an array list of data points with known and interpolated temperatures.
Created a test that checks for correct interpolated values and verifies that all data points in the array list have a temperature value.

2024-04-24 22:28 UTC, sechols223 requested changes
Change

2024-04-24 22:33 UTC, sechols223 commented
PR name is questionable

2024-04-25 02:06 UTC, alemmond commented
updated to account for depth as well as to be able to read 3d array list as input

2024-04-25 02:11 UTC, sechols223 requested changes
Make changes

2024-04-25 02:11 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/InverseWeightedDataInterpolator.java
> +                .collect(Collectors.toList());
Good job :)

2024-04-25 02:11 UTC, sechols223 commented on src/test/java/com/github/gissuite/gribinterpolation/InverseWeightedDataInterpolatorTest.java
> +                        System.out.print("(" + point.getLatitude() + ", " + point.getLongitude() + ", " + point.getTemperatureK() + ", " + point.getDepth() + ") ");
Don't print in unit tests

2024-04-25 02:11 UTC, sechols223 commented on src/test/java/com/github/gissuite/gribinterpolation/InverseWeightedDataInterpolatorTest.java
> +        //check that InverseWeightedDataInterpolator returns the correct data points
Remove commented code

2024-04-25 02:13 UTC, alemmond commented on src/main/java/com/github/gissuite/gribinterpolation/core/InverseWeightedDataInterpolator.java
> +                .collect(Collectors.toList());
that was hard to figure out the 3d part

2024-04-25 02:13 UTC, alemmond commented on src/test/java/com/github/gissuite/gribinterpolation/InverseWeightedDataInterpolatorTest.java
> +                        System.out.print("(" + point.getLatitude() + ", " + point.getLongitude() + ", " + point.getTemperatureK() + ", " + point.getDepth() + ") ");
oh right i just did this to double check sorry!

2024-04-25 02:14 UTC, alemmond commented on src/test/java/com/github/gissuite/gribinterpolation/InverseWeightedDataInterpolatorTest.java
> +        //check that InverseWeightedDataInterpolator returns the correct data points
oops lol

2024-04-25 02:14 UTC, sechols223 commented on src/main/java/com/github/gissuite/gribinterpolation/core/InverseWeightedDataInterpolator.java
> +                .collect(Collectors.toList());
I know and I'm happy your were able to figure it out

2024-04-25 02:15 UTC, sechols223 approved these changes

2024-04-25 02:18 UTC, merged